user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;
events{}
http {
    include /etc/nginx/conf.d/nginx_geo_russia_blocklist.conf;
    server{
	listen 80;
    error_page 403 /sorry.html;
    location = /sorry.html {
            root /data;
            internal;
        }
	location / {
        if ($blacklist){
            return 403;
        }
	    proxy_pass http://localhost:7777;
	}
    }
}


